// Code generated by "stringer -linecomment -type Severity -output severity_string.go"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeverityNone-0]
	_ = x[SeverityOK-1]
	_ = x[SeverityDebug-2]
	_ = x[SeverityInfo-3]
	_ = x[SeverityNotice-4]
	_ = x[SeverityWarning-5]
	_ = x[SeverityErr-6]
	_ = x[SeverityCrit-7]
	_ = x[SeverityAlert-8]
	_ = x[SeverityEmerg-9]
	_ = x[severityMax-10]
}

const _Severity_name = "noneokdebuginfonoticewarningerrcritalertemerginternal"

var _Severity_index = [...]uint8{0, 4, 6, 11, 15, 21, 28, 31, 35, 40, 45, 53}

func (i Severity) String() string {
	if i >= Severity(len(_Severity_index)-1) {
		return "Severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Severity_name[_Severity_index[i]:_Severity_index[i+1]]
}
