// Code generated by "stringer -linecomment -type Type -output type_string.go"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeAcknowledgementCleared-1]
	_ = x[TypeAcknowledgementSet-2]
	_ = x[TypeCustom-3]
	_ = x[TypeIncidentAge-4]
	_ = x[TypeMute-5]
	_ = x[TypeState-6]
	_ = x[TypeUnmute-7]
	_ = x[typeMax-8]
}

const _Type_name = "unknownacknowledgement-clearedacknowledgement-setcustomincident-agemutestateunmuteinternal"

var _Type_index = [...]uint8{0, 7, 30, 49, 55, 67, 71, 76, 82, 90}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
